version: "2.4"

services:

  xnode-dev: 
    build:
      context: "./node"  # same dir, just in the dev folder structure
    network_mode: "host"
    profiles: ["xnode-dev"]

  xnode-prod: 
    build:
      context: "./node-prod"
    network_mode: "host"
    profiles: ["xnode-prod"]

  btc:
    build:
      context: "./extnodes/btc"
    network_mode: "host"
    ports:
      - "127.0.0.1:5000:5000"
      - "8333:8333" # Definitely subject to change once go chain implementation is done
    mem_limit: 2000000000
    profiles: ["btc"]

  eth:
    build: 
      context: "./extnodes/eth"
    ports:
      - "30303:30303" 
      - "127.0.0.1:5001:5001"
    mem_limit: 1000000000
    profiles: ["eth"]

  bch:
    build: 
      context: "./extnodes/bch"
    network_mode: "host"
    ports:
      - "8333:8333" 
      - "127.0.0.1:5002:5002"
    mem_limit: 2000000000
    profiles: ["bch"]

  ltc:
    build:
      context: "./extnodes/ltc"
    network_mode: "host"
    ports:
      - "9333:9333"
      - "127.0.0.1:5003:5003"
    mem_limit: 2000000000
    profiles: ["ltc"]

  doge:
    build: 
      context: "./extnodes/doge"
    network_mode: "host"
    ports:
      - "22556:22556" 
      - "127.0.0.1:5004:5004"
    mem_limit: 2000000000
    profiles: ["doge"]

  xmr:
    build: 
      context: "./extnodes/xmr"
    ports:
      - "18080:18080" 
      - "127.0.0.1:5005:5005"
    mem_limit: 500000000
    profiles: ["xmr"]

  zec:
    build: 
      context: "./extnodes/zec"
    ports:
      - "8233:8233" 
      - "127.0.0.1:5006:5006"
    mem_limit: 500000000
    profiles: ["zec"]
