version: "2.4"

services:
  btc:
    build:
      context: "./extnodes/btc"
    ports:
      - "8333:8333" # Definitely subject to change once go chain implementation is done
    mem_limit: 500000000
    expose:
      - "5000"
    profiles: ["btc"]
  eth:
    build: 
      context: "./extnodes/eth"
    ports:
      - "30303:30303" 
    expose:
      - "5001"
    mem_limit: 50000000
    profiles: ["eth"]
  bch:
    build: 
      context: "./extnodes/bch"
    ports:
      - "8333:8333" 
    expose:
      - "5002"
    mem_limit: 500000000
    profiles: ["bch"]
  doge:
    build: 
      context: "./extnodes/doge"
    ports:
      - "22556:22556" 
    expose:
      - "5003"
    mem_limit: 500000000
    profiles: ["doge"]
  xmr:
    build: 
      context: "./extnodes/xmr"
    ports:
      - "18080:18080" 
    expose:
      - "5004"
    mem_limit: 500000000
    profiles: ["xmr"]
  zec:
    build: 
      context: "./extnodes/zec"
    ports:
      - "8233:8233" 
    expose:
      - "5005"
    mem_limit: 500000000
    profiles: ["zec"]
